"""
Django settings for catshelter project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=)pv+w0r4o)9$@x=&_*qyl*x5)nh!fdbf)^l4(19$gt(c$=h9y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STATIC_ROOT = "/home/ubuntu/media/staticfiles/"
STATIC_URL = 'https://thanhdevops.info/static/'

ALLOWED_HOSTS = ['172.31.45.204','catshelter.thanhdevops.info','13.60.180.237','13.49.68.114','thanhdevops.info','www.thanhdevops.info','www.catshelter.thanhdevops.info']

CSRF_TRUSTED_ORIGINS = [
    'https://thanhdevops.info',
    'https://www.thanhdevops.info',
    'https://www.catshelter.thanhdevops.info',
    'https://catshelter.thanhdevops.info',  # Add other trusted origins here
]


# Application definition

INSTALLED_APPS = [
    'accounts',
    'catshelter',
    'storages',
    'landing',
    'django_extensions',
    'django.contrib.admin',
    'django_hosts',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

#DEFAULT_FILE_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
DEFAULT_FILE_STORAGE = 'catshelter.sftp_storage.CustomSFTPStorage'


#STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

#STATIC_ROOT = BASE_DIR / 'staticfiles'  # Absolute path to static files directory

# Media files (user uploads)
DEFAULT_FILE_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'

DEFAULT_FILE_STORAGE = 'storages.backends.sftp.SFTPStorage'

SFTP_STORAGE_OPTIONS = {
    'host': 'thanhdevops.info',
    'port': 22,
    'username': 'ubuntu',
    'password': 'm4st3r',  # Comment out if using key-based auth
    #'private_key': '/path/to/private/key.pem',  # Comment out if using password-based auth
    'root': '/home/ubuntu/media/',
}


MEDIA_URL = 'https://catshelter.thanhdevops.info/media/'
MEDIA_ROOT = BASE_DIR / 'media'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsRequestMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

ROOT_URLCONF = 'thanhdevops.urls'
ROOT_HOSTCONF = 'thanhdevops.hosts'
#DEFAULT_HOST = 'default'
DEFAULT_HOST = 'www'

PARENT_HOST = 'thanhdevops.info'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catshelter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mycat',
        'USER': 'postgres',
	'PASSWORD': 'm4st3r',
	'HOST': '13.60.180.237',
	'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


