# Generated by Django 5.0.8 on 2024-08-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feline',
            fields=[
                ('feline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('fav_toy', models.CharField(max_length=100)),
                ('coloration', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cats_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkupdate', models.DateField()),
                ('treatment', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=50)),
                ('feline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='catshelter.feline')),
            ],
        ),
    ]
