name: Django Health Check

# Trigger the workflow on push to master or on pull requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  health-check:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    services:
      postgres:
        image: postgres:13  # Set up a PostgreSQL service
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: m4st3r
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:m4st3r@13.60.180.237:5432/test_db  # Database connection string

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate  # Apply migrations

    - name: Start Django server
      run: |
        python manage.py runserver 0.0.0.0:8000 &  # Start Django server in the background
      env:
        DJANGO_SETTINGS_MODULE: thanhdevops.settings  # Replace with your settings module if needed

    - name: Health check with curl
      run: |
        sleep 10  # Wait a few seconds for the server to start
        curl --fail http://13.49.68.114:8000  # Check if the Django site is up
